"""add

Revision ID: 395627868af5
Revises: None
Create Date: 2013-09-05 22:17:40.847101
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '395627868af5'
down_revision = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
