"""add description

Revision ID: c25fa5e6cd7
Revises: 3c29ba663ce8
Create Date: 2013-09-05 23:32:22.561176
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision = 'c25fa5e6cd7'
down_revision = '3c29ba663ce8'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'user')
    op.add_column('users', sa.Column('description', sa.String(length=140), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    op.create_table(u'user',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'name', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
